# Generated by Django 4.1.3 on 2022-12-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('Codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Duracion', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('Codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('Creditos', models.IntegerField(max_length=1, verbose_name='Creditos')),
                ('Docente', models.CharField(max_length=100, verbose_name='Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('Cedula', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cédula')),
                ('Apellido_paterno', models.CharField(max_length=15, verbose_name='Apellido Materno')),
                ('Apellido_materno', models.CharField(max_length=15, verbose_name='Apellido paterno')),
                ('Nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('FechaNacimiento', models.DateField(max_length=15, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('Vigencia', models.IntegerField(choices=[(1, 'Vigente'), (0, 'No vigente')], verbose_name='Vigencia')),
                ('CodigoCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniapp.carrera', verbose_name='Codigo de carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_estudiante', models.DateField(verbose_name='Fecha de matricula')),
                ('Codigo_Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniapp.curso')),
                ('id_Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniapp.estudiantes')),
            ],
        ),
    ]
