# Generated by Django 4.1.3 on 2022-12-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='Duracion',
            field=models.IntegerField(verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='Creditos',
            field=models.IntegerField(verbose_name='Creditos'),
        ),
        migrations.DeleteModel(
            name='Matriculas',
        ),
    ]
