# Generated by Django 4.1.3 on 2022-12-15 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0002_alter_carrera_duracion_alter_curso_creditos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_estudiante', models.DateField(verbose_name='Fecha de matricula')),
                ('Codigo_Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniapp.carrera')),
                ('id_Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniapp.estudiantes')),
            ],
        ),
    ]
