# Generated by Django 4.1.3 on 2022-12-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0003_matricula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
