# Generated by Django 4.1.3 on 2022-12-16 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0006_remove_matricula_codigo_carrera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('Matricula', models.CharField(max_length=12, verbose_name='Matricula')),
                ('Cedula', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cédula')),
                ('Apellido_paterno', models.CharField(max_length=15, verbose_name='Apellido Materno')),
                ('Apellido_materno', models.CharField(max_length=15, verbose_name='Apellido paterno')),
                ('Nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('FechaNacimiento', models.DateField(max_length=15, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('Vigencia', models.IntegerField(choices=[(1, 'Vigente'), (0, 'No vigente')], verbose_name='Vigencia')),
                ('CodigoCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniapp.carrera', verbose_name='Codigo de carrera')),
            ],
        ),
    ]
